# Site settings
title: Travis Hohl | Technical Consultant
email: travis@travishohl.com
description: >
    Technical consulting for small businesses. I help companies build better systems by finding root causes and delivering measurable outcomesâ€”not just code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://travishohl.com" # the base hostname & protocol for your site
github_username: travishohl

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed
  load_paths:
    - _sass
